package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "projects")
data class CmsProject(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val description: String,
    val techStack: String = "Flutter Visual Suite",
    val githubRepo: String = "owner/my-cms-builder-site",
    val githubBranch: String = "main",
    val githubToken: String = "",
    val activeModules: String = "Blog,Users,AI", // Comma separated, e.g. "Blog,Users,Gallery,Shop,CRM,Wiki,AI,Analytics"
    val customSchemaJson: String = "[]", // Custom JSON data fields generated by the dynamic AI Schema editor
    val hasPwa: Boolean = true,
    val hasDocker: Boolean = true,
    val hasActions: Boolean = true,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
